name: susanvargascreative
favicon: null
layout_spectrum: 0.9801397151313722
typography_spectrum: 0.9900419330224395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.20130537450313568
  lightness: 0.5203226683661342
  saturation: 0.6706717512570322
  rhythmicContrast: 0.28987079206854105
purpose: []
